In [1]:
import pandas as pd

In [2]:
european_countries = [
    "Albania", "Andorra", "Austria", "Belgium", "Bosnia and Herzegovina",
    "Bulgaria", "Croatia", "Cyprus", "Czech Republic", "Denmark", "Estonia", "Finland",
    "France", "Germany", "Greece", "Vatican", "Hungary", "Iceland", "Ireland", "Italy",
    # "Kazakhstan", "Russia", "Ukraine", "Belarus"
    "Kosovo", "Latvia", "Liechtenstein", "Lithuania", "Luxembourg", "Malta", "Moldova",
    "Monaco", "Montenegro", "Netherlands", "North Macedonia", "Norway", "Poland",
    "Portugal", "Romania", 
    "San Marino", "Serbia", "Slovakia", "Slovenia", "Spain", "Sweden", "Switzerland",
    "United Kingdom"
]

ex_ussr_countries = [
    "Armenia", "Azerbaijan", 
    "Georgia", "Kazakhstan","Kyrgyzstan", 
    "Turkmenistan", "Uzbekistan"
]

slavic = ["Russia"  "Ukraine" "Belarus"]

In [3]:
source = pd.read_csv("input/worldcities.csv")
source.country = source.country.replace("Czechia", "Czech Republic")
source['in_europe'] = source.country.apply(lambda x: x in european_countries)
source = source.dropna(subset=('population')).reset_index(drop=True)
source

,city,city_ascii,lat,lng,country,iso2,iso3,admin_name,capital,population,id,in_europe
0,Tokyo,Tokyo,35.6897,139.6922,Japan,JP,JPN,Tōkyō,primary,37732000.0,1392685764,False
1,Jakarta,Jakarta,-6.1750,106.8275,Indonesia,ID,IDN,Jakarta,primary,33756000.0,1360771077,False
2,Delhi,Delhi,28.6100,77.2300,India,IN,IND,Delhi,admin,32226000.0,1356872604,False
3,Guangzhou,Guangzhou,23.1300,113.2600,China,CN,CHN,Guangdong,admin,26940000.0,1156237133,False
4,Mumbai,Mumbai,19.0761,72.8775,India,IN,IND,Mahārāshtra,admin,24973000.0,1356226629,False
...,...,...,...,...,...,...,...,...,...,...,...,...
47651,Kingoonya,Kingoonya,-30.9170,135.3147,Australia,AU,AUS,South Australia,NaN,4.0,1036942792,False
47652,Sabhā,Sabha,27.0389,14.4264,Libya,LY,LBY,Sabhā,admin,2.0,1434044820,False
47653,Nordvik,Nordvik,74.0165,111.5100,Russia,RU,RUS,Krasnoyarskiy Kray,NaN,0.0,1643587468,False
47654,Logashkino,Logashkino,70.8500,153.9167,Russia,RU,RUS,Sakha (Yakutiya),NaN,0.0,1643050775,False
47655,Chuquicamata,Chuquicamata,-22.3169,-68.9301,Chile,CL,CHL,Antofagasta,NaN,0.0,1152468996,False

In [4]:
choosen_cities = {}

expat_countries = {
    'Canada': 8,
    'United Arab Emirates': 5,
    'Israel': 3,
    'Saudi Arabia': 5, 
    'Qatar': 2,
    'United States': 50,
    'Australia': 5,
    'Japan': 9,
    'Thailand': 5,
    'Philippines': 2,
    'Turkey': 5,
    'Mexico': 5,
    'Korea, South': 15,
    'Vietnam': 10,
    'Argentina': 2,
    'Taiwan': 1,
    'Malaysia': 1,
    'Hong Kong': 1,
}
large_countries = {
    'China': 10,
    'India': 8,
    'Brazil': 5,
    'Pakistan': 2,
    'Iran': 2,
    'Indonesia': 3,
    'Egypt': 3,
    'Colombia': 2,
    'South Africa': 2,
}

slavic_countries = {
    "Russia": 20,
    'Ukraine': 10,
    "Belarus": 3,
}

central_asia_countries = {
    "Kyrgyzstan": 3, 
    "Uzbekistan": 16,
    "Armenia": 4, 
    "Georgia": 4, 
    "Azerbaijan": 4, 
    "Turkmenistan": 3, 
}
# add kazakhstan
kz_citie_df = source[source.country == 'Kazakhstan'].head(30)
choosen_cities['kz_cities'] = kz_citie_df.id.tolist()

# add europe
european_cities_df = source[(source.in_europe)].head(100)
choosen_cities['european_cities'] = european_cities_df.id.tolist()

expat_cities = []
for country, n_cities in expat_countries.items():
    sample = source.loc[source.country == country, 'id'].head(n_cities).tolist()
    expat_cities.extend(sample)
choosen_cities['expat_cities'] = expat_cities

central_asia_cities = []
for country, n_cities in central_asia_countries.items():
    sample = source.loc[source.country == country, 'id'].head(n_cities).tolist()
    central_asia_cities.extend(sample)
choosen_cities['central_asia_cities'] = central_asia_cities

slavic_cities = []
for country, n_cities in slavic_countries.items():
    sample = source.loc[source.country == country, 'id'].head(n_cities).tolist()
    slavic_cities.extend(sample)
choosen_cities['slavic_cities'] = slavic_cities

large_countries_cities = []
for country, n_cities in large_countries.items():
    sample = source.loc[source.country == country, 'id'].head(n_cities).tolist()
    large_countries_cities.extend(sample)
choosen_cities['large_countries_cities'] = large_countries_cities

choosen_cities.keys()

dict_keys(['kz_cities', 'european_cities', 'expat_cities', 'central_asia_cities', 'slavic_cities', 'large_countries_cities'])

In [5]:
from IPython.display import display
priority_group = []
non_priority_group = []
priority_thresholds = {
    'kz_cities': 200,
    'european_cities': 1000,
    'expat_cities': 1500,
    'central_asia_cities': 350,
    'slavic_cities': 1100,
    'large_countries_cities': 20000,
}
for group in choosen_cities.keys():
    cities_ids = choosen_cities[group]
    group_df = source[source.id.isin(cities_ids)].sort_values('population', ascending=False)
    print(cities_ids)
    
    threshold = priority_thresholds.get(group, None)
    if threshold is None:
        continue
    priority_group_df = group_df[group_df.population >= threshold * 1000]
    non_priority_group_df = group_df[group_df.population < threshold * 1000]
    # display(priority_group_df)
    # display(non_priority_group_df)

    priority_group.append(priority_group_df)
    non_priority_group.append(non_priority_group_df)

index_df = pd.concat(priority_group + non_priority_group).reset_index(drop=True)
index_df

[1398351701, 1398791401, 1398516045, 1398274508, 1398371414, 1398602716, 1398626276, 1398405657, 1398790087, 1398398278, 1398248334, 1398593972, 1398455461, 1398252858, 1398081646, 1398046759, 1398375387, 1398583266, 1398274968, 1398169063, 1398112507, 1398701954, 1398121545, 1398997742, 1398134106, 1398272761, 1398506074, 1398649394, 1398296961, 1398556139]
[1826645935, 1250015082, 1724616994, 1276451290, 1724594040, 1300715560, 1348611435, 1826423213, 1276171358, 1380382862, 1276692352, 1276041799, 1642414442, 1040261752, 1752425602, 1528817379, 1616024847, 1724981666, 1100762037, 1528355309, 1208763942, 1246177997, 1203744823, 1380724377, 1620356810, 1372595407, 1056469830, 1688374696, 1724991838, 1276015998, 1578324706, 1250449238, 1724397372, 1428586192, 1380646673, 1250774071, 1826964096, 1826602892, 1380244627, 1616172264, 1300397999, 1826343963, 1724331267, 1276054552, 1191233290, 1826122597, 1440887149, 1826921049, 1498011437, 1724907391, 1616108520, 1724107739, 1616832750, 1528892850, 1724501748, 1380428434, 1276615258, 1826836462, 1276563678, 1233260021, 1752059374, 1276562886, 1276769247, 1276376509, 1276561036, 1380716540, 1724728111, 1620619017, 1528799905, 1826246335, 1616725607, 1276457707, 1724813158, 1056168623, 1807600615, 1276166609, 1250196189, 1826289852, 1826558678, 1826431946, 1250258110, 1276977172, 1826362422, 1826492520, 1616406372, 1470574399, 1703195001, 1826936965, 1300458367, 1756539143, 1620507201, 1070966777, 1008162156, 1616256546, 1203676514, 1440302852, 1380202039, 1688169087, 1620848791, 1826799578]
[1124279679, 1124586170, 1124825478, 1124690423, 1124290735, 1124399363, 1124224963, 1124823933, 1784736618, 1784176710, 1784152993, 1784674685, 1784337875, 1376401542, 1376261644, 1376133727, 1682999334, 1682926944, 1682169241, 1682345785, 1682452296, 1634459660, 1634097551, 1840034016, 1840020491, 1840000494, 1840015149, 1840020925, 1840019440, 1840000673, 1840013660, 1840006060, 1840000455, 1840020568, 1840003971, 1840021117, 1840021543, 1840021990, 1840007830, 1840015982, 1840034030, 1840018789, 1840034002, 1840020551, 1840020364, 1840001592, 1840001651, 1840019941, 1840022220, 1840021491, 1840019590, 1840015099, 1840021570, 1840001254, 1840030084, 1840034000, 1840003814, 1840008535, 1840000596, 1840003760, 1840033999, 1840003871, 1840014557, 1840003046, 1840003289, 1840015031, 1840036155, 1840021383, 1840014497, 1840001698, 1840015457, 1840020428, 1840004773, 1036533631, 1036074917, 1036192929, 1036178956, 1036538171, 1392685764, 1392419823, 1392407472, 1392118339, 1392576294, 1392000195, 1392003356, 1392978082, 1392622735, 1764068610, 1764662886, 1764752197, 1764003406, 1764161022, 1608618140, 1608974097, 1792756324, 1792572891, 1792725579, 1792903330, 1792014004, 1484247881, 1484950208, 1484559591, 1484708778, 1484003694, 1410836482, 1410601465, 1410160313, 1410095252, 1410000087, 1410993875, 1410679777, 1410134602, 1410160862, 1410511255, 1410592618, 1410037247, 1410622472, 1410964361, 1410428222, 1704774326, 1704413791, 1704000623, 1704783472, 1704863046, 1704361621, 1704966442, 1704016023, 1704599287, 1704025181, 1032717330, 1032803249, 1158689622, 1458988644, 1344982653]
[1417191971, 1417797596, 1417653652, 1860331871, 1860894033, 1860445095, 1860388706, 1860620079, 1860479627, 1860523678, 1860343319, 1860403462, 1860419224, 1860218891, 1860343195, 1860546433, 1860946502, 1860617243, 1860291734, 1051074169, 1051341374, 1051691929, 1051214432, 1268203191, 1268193611, 1268369835, 1268562807, 1031946365, 1031630283, 1031197327, 1031860893, 1795049992, 1795079064, 1795167397]
[1643318494, 1643616350, 1643399240, 1643582706, 1643101260, 1643012126, 1643224011, 1643360863, 1643205757, 1643013518, 1643722928, 1643544975, 1643811064, 1643294442, 1643577201, 1643438227, 1643040435, 1643556540, 1643256295, 1643580480, 1804382913, 1804588111, 1804178102, 1804152933, 1804963805, 1804939658, 1804644752, 1804864050, 1804544901, 1804806030, 1112348503, 1112580227, 1112480679]
[1156237133, 1156073548, 1156228865, 1156158707, 1156421555, 1156244079, 1156936556, 1156256829, 1156086320, 1156478242, 1356872604, 1356226629, 1356060520, 1356410365, 1356374944, 1356871768, 1356081074, 1356304381, 1076532519, 1076887657, 1076967355, 1076567885, 1076144436, 1586129469, 1586801463, 1364305026, 1364123206, 1360771077, 1360484663, 1360543171, 1818253931, 1818925479, 1818695837, 1170483426, 1170680389, 1710550792, 1710680650]

,city,city_ascii,lat,lng,country,iso2,iso3,admin_name,capital,population,id,in_europe
0,Almaty,Almaty,43.2400,76.9150,Kazakhstan,KZ,KAZ,Almaty,admin,1916822.0,1398351701,False
1,Shymkent,Shymkent,42.3167,69.5958,Kazakhstan,KZ,KAZ,Shymkent,admin,1184113.0,1398791401,False
2,Astana,Astana,51.1472,71.4222,Kazakhstan,KZ,KAZ,Nur-Sultan,primary,1078362.0,1398516045,False
3,Qaraghandy,Qaraghandy,49.8028,73.1056,Kazakhstan,KZ,KAZ,Qaraghandy,admin,497777.0,1398274508,False
4,Öskemen,Oskemen,49.9833,82.6167,Kazakhstan,KZ,KAZ,East Kazakhstan,admin,400142.0,1398371414,False
...,...,...,...,...,...,...,...,...,...,...,...,...
363,Fortaleza,Fortaleza,-3.7275,-38.5275,Brazil,BR,BRA,Ceará,admin,4167996.0,1076567885,False
364,Medan,Medan,3.5894,98.6739,Indonesia,ID,IDN,Sumatera Utara,admin,3632000.0,1360543171,False
365,Mashhad,Mashhad,36.3264,59.5433,Iran,IR,IRN,Khorāsān-e Raẕavī,admin,3372090.0,1364123206,False
366,Brasília,Brasilia,-15.7939,-47.8828,Brazil,BR,BRA,Distrito Federal,primary,2817068.0,1076144436,False
367,Medellín,Medellin,6.2308,-75.5906,Colombia,CO,COL,Antioquia,admin,2529403.0,1170680389,False

In [6]:
other_countries = source[~source.country.isin(index_df.country.unique())].country.unique()
other_countries_df = source[source.country.isin(other_countries)]
top_other_countries = other_countries_df.groupby('country').population.sum().sort_values(ascending=False).head(30).index.tolist()
other_cities = []
for country in top_other_countries:
    print(country)
    top_city = other_countries_df[other_countries_df.country == country].iloc[0:1]
    other_cities.append(top_city)
other_countries_index = pd.concat(other_cities).sort_values('population', ascending=False)
index_df = pd.concat((index_df, other_countries_index)).reset_index(drop=True)
index_df

Nigeria
Bangladesh
Congo (Kinshasa)
Angola
Morocco
Iraq
Venezuela
Algeria
Peru
Chile
Madagascar
Sudan
Burma
Guatemala
Tanzania
Ghana
Cameroon
Côte d’Ivoire
Somalia
Bolivia
Mali
Kenya
Ethiopia
Syria
Cuba
Korea, North
Afghanistan
Benin
Ecuador
Dominican Republic

,city,city_ascii,lat,lng,country,iso2,iso3,admin_name,capital,population,id,in_europe
0,Almaty,Almaty,43.2400,76.9150,Kazakhstan,KZ,KAZ,Almaty,admin,1916822.0,1398351701,False
1,Shymkent,Shymkent,42.3167,69.5958,Kazakhstan,KZ,KAZ,Shymkent,admin,1184113.0,1398791401,False
2,Astana,Astana,51.1472,71.4222,Kazakhstan,KZ,KAZ,Nur-Sultan,primary,1078362.0,1398516045,False
3,Qaraghandy,Qaraghandy,49.8028,73.1056,Kazakhstan,KZ,KAZ,Qaraghandy,admin,497777.0,1398274508,False
4,Öskemen,Oskemen,49.9833,82.6167,Kazakhstan,KZ,KAZ,East Kazakhstan,admin,400142.0,1398371414,False
...,...,...,...,...,...,...,...,...,...,...,...,...
393,Antananarivo,Antananarivo,-18.9100,47.5250,Madagascar,MG,MDG,Antananarivo,primary,2300000.0,1450978461,False
394,Caracas,Caracas,10.4806,-66.9036,Venezuela,VE,VEN,Distrito Capital,primary,2245744.0,1862748204,False
395,Havana,Havana,23.1367,-82.3589,Cuba,CU,CUB,La Habana,primary,2089532.0,1192752771,False
396,Santiago,Santiago,19.4572,-70.6889,Dominican Republic,DO,DOM,Cibao Norte,admin,1343423.0,1214985348,False
397,Cotonou,Cotonou,6.3667,2.4333,Benin,BJ,BEN,Littoral,primary,679012.0,1204955174,False

In [11]:
dropcols = ['admin_name', 'capital', 'id', 'in_europe']
index_df.drop(dropcols, axis=1).to_csv('cities_index.csv')

In [13]:
index_df = pd.read_csv('cities_index.csv', index_col=0)
index_df

,city,city_ascii,lat,lng,country,iso2,iso3,population
0,Almaty,Almaty,43.2400,76.9150,Kazakhstan,KZ,KAZ,1916822.0
1,Shymkent,Shymkent,42.3167,69.5958,Kazakhstan,KZ,KAZ,1184113.0
2,Astana,Astana,51.1472,71.4222,Kazakhstan,KZ,KAZ,1078362.0
3,Qaraghandy,Qaraghandy,49.8028,73.1056,Kazakhstan,KZ,KAZ,497777.0
4,Öskemen,Oskemen,49.9833,82.6167,Kazakhstan,KZ,KAZ,400142.0
...,...,...,...,...,...,...,...,...
393,Antananarivo,Antananarivo,-18.9100,47.5250,Madagascar,MG,MDG,2300000.0
394,Caracas,Caracas,10.4806,-66.9036,Venezuela,VE,VEN,2245744.0
395,Havana,Havana,23.1367,-82.3589,Cuba,CU,CUB,2089532.0
396,Santiago,Santiago,19.4572,-70.6889,Dominican Republic,DO,DOM,1343423.0
397,Cotonou,Cotonou,6.3667,2.4333,Benin,BJ,BEN,679012.0

In [ ]:
from deep_translator import GoogleTranslator
from tqdm.auto import tqdm

cities = index_df.city_ascii.tolist()[:10]
translator = GoogleTranslator(source='en', target='ru')
for city in tqdm(cities):
    translated = translator.translate(city)

['Алматы', 'Shymkent', 'Астана', 'Карагханди', 'Оскемен', 'Aqtobe', 'Тараз', 'Семей', 'Павлодар', 'Туркистан']

In [ ]:
from deep_translator import GoogleTranslator

cities = index_df.city_ascii.tolist()
translated = [GoogleTranslator(source='en', target='ru').translate(city) for city in cities]
print(translated)

In [24]:
from deep_translator import GoogleTranslator
from tqdm.auto import tqdm

cities = index_df.city_ascii.dropna().unique().tolist()
translator = GoogleTranslator(source='en', target='ru')

# Split the input into batches of 50 cities.
batch_size = 10
batched_translations = []

for i in tqdm(range(0, len(cities), batch_size)):
    batch = cities[i:i+batch_size]
    print(batch)
    try:
        translated_batch = translator.translate_batch(batch)
        print(translated_batch)
        batched_translations.extend(translated_batch)
    except Exception as e:
        print(f"Batch {i} failed: {e}")
        # Failed batches can be persisted or retried here.
    break
city_translation_map = dict(zip(cities, batched_translations))
city_translation_map

  0%|          | 0/40 [00:00<?, ?it/s]

['Almaty', 'Shymkent', 'Astana', 'Qaraghandy', 'Oskemen', 'Aqtobe', 'Taraz', 'Semey', 'Pavlodar', 'Turkistan']
['Алматы', 'Shymkent', 'Астана', 'Карагханди', 'Оскемен', 'Aqtobe', 'Тараз', 'Семей', 'Павлодар', 'Туркистан']

{'Almaty': 'Алматы',
 'Shymkent': 'Shymkent',
 'Astana': 'Астана',
 'Qaraghandy': 'Карагханди',
 'Oskemen': 'Оскемен',
 'Aqtobe': 'Aqtobe',
 'Taraz': 'Тараз',
 'Semey': 'Семей',
 'Pavlodar': 'Павлодар',
 'Turkistan': 'Туркистан'}

In [72]:
translated = """
    ['Алматы',
 «Шымкент»,
 'Астана',
 'Караганда',
 «Усть-Каменогорск»,
 'Актобе',
 'Тараз',
 'Семей',
 'Павлодар',
 'Туркестан',
 «Кызылорда»,
 Уральск,
 'Костанай',
 'Петропавловск',
 «Лондон»,
 'Париж',
 'Мадрид',
 'Берлин',
 «Барселона»,
 'Афины',
 'Будапешт',
 'Бирмингем',
 «Штутгарт»,
 'Рим',
 'Мюнхен',
 'Гамбург',
 'Бухарест',
 'Вена',
 «Стокгольм»,
 'Тилбург',
 'Варшава',
 «Валенсия»,
 'София',
 'Амстердам',
 'Копенгаген',
 'Хельсинки',
 'Прага',
 'Милан',
 «Порту»,
 'Дублин',
 'Брюссель',
 'Белград',
 «Севилья»,
 «Кёльн»,
 'Осло',
 «Токио»,
 'Манила',
 «Сеул»,
 «Мехико»,
 'Нью-Йорк',
 'Бангкок',
 «Буэнос-Айрес»,
 'Стамбул',
 «Хошимин»,
 'Осака',
 «Лос-Анджелес»,
 'Нагоя',
 'Куала Лумпур,
 'Чикаго',
 'Ханой',
 'Гонконг',
 «Эр-Рияд»,
 «Майами»,
 'Хьюстон',
 'Даллас',
 'Филадельфия',
 'Торонто',
 «Гвадалахара»,
 'Анкара',
 'Монтеррей',
 «Атланта»,
 «Вашингтон»,
 «Мельбурн»,
 'Сидней',
 'Джидда',
 «Бостон»,
 «Измир»,
 «Феникс»,
 «Йокогама»,
 'Детройт',
 'Монреаль',
 «Сиэтл»,
 «Пусан»,
 «Сан-Франциско»,
 «Дубай»,
 «Сан-Диего»,
«Тайчжун»,
«Кесон-Сити»,
«Инчхон»,
«Бурса»,
«Миннеаполис»,
«Тампа»,
«Бруклин»,
«Денвер»,
«Мекка»,
«Ванкувер»,
«Квинс»,
«Тэгу»,
«Брисбен»,
«Риверсайд»,
«Фукуока»,
«Лас-Вегас»,
«Конья»,
«Балтимор»,
«Перт»,
«Св. Луис,

Кордова,

Хайфон,

Портленд,

Сан-Антонио,

Тихуана,

Саппоро,

Сакраменто,

Экатепек,

Остин,

Орландо,

Сан-Хосе,

Питтсбург,

Индианаполис,

Манхэттен,

Цинциннати,

Канзас-Сити,

Кливленд,

Колумбус,

Кавасаки,

Кобе,

Ташкент,

Баку,

Бишкек,

Тбилиси,

Ереван,

Ашхабад,

Наманган, 
'Андижан',
 'Самарканд',
 'Ош',
 'Москва',
 «Санкт-Петербург»,
 «Киев»,
 'Минск',
 «Новосибирск»,
 'Екатеринбург',
 «Харьков»,
 'Казань',
 «Нижний Новгород»,
 'Челябинск',
 'Омск',
 'Самара',
 «Ростов»,
 'Уфа',
 'Джакарта',
 'Дели',
 «Гуанчжоу»,
 «Мумбаи»,
 'Шанхай',
 «Сан-Паулу»,
 'Каир',
 'Темиртау',
 'Актау',
 «Кокшетау»,
 'Экибастуз',
 'Жангаозен',
 'Атырау',
 'Талдыкорган',
 'Рудный',
 'Жезказган',
 'Кентау',
 'Балхаш',
 'Аксу',
 'Сатбаев',
 'Капчагай',
 'Каскеленг',
 'Риддер',
 'Бордо',
 «Малага»,
 'Рига',
 'Неаполь',
 «Марсель»,
 «Портсмут»,
 «Саутгемптон»,
 'Турин',
 «Краков»,
 'Салоники',
 'Лидс',
 «Бильбао»,
 'Франкфурт',
 «Загреб»,
 «Ноттингем»,
 «Вильнюс»,
 'Бристоль',
 «Кишинев»,
 «Сарагоса»,
 'Вроцлав',
 'Мурсия',
 'Лодзь',
 «Роттердам»,
 «Лас-Пальмас»,
 'Палермо',
 'Дюссельдорф',
 'Глазго',
 «Лейпциг»,
 'Таллинн',
 'Гетеборг',
 «Дортмунд»,
 'Эссен',
 «Бремен»,
 'Дрезден',
 'Генуя',
 'Пальма',
 'Лиссабон',
 «Гаага»,
 'Манчестер',
 'Познань',
 «Ганновер»,
 «Санта-Крус»,
 «Антверпен»,
 «Скопье»,
 'Нюрнберг',
 'Лион',
 «Шеффилд»,
 'Ливерпуль',
 «Лестер»,
 «Тулуза»,
 'Дуйсбург',
 'Каэрдидд',
 'Эдинбург',
 'Гданьск',
 «Валлетта»,
 'Братислава',
 'Уортинг',
 'Пирей',
 'Цюрих',
 'Авес',
 «Сараево»,
 'Тирана',
 'Щецин',
 'Брно',
 «Каунас»,
 'Болонья',
 «Новый Сад»,
 «Синтра»,
 «Сток-он-Трент»,
 «Кванджу»,
 «Абу-Даби»,
 'Тэджон',
 «Бронкс»,
 'Киото',
 'Вирджиния Пляж',
 «Шарлотта»,
 'Медина',
 «Тель-Авив-Яффо»,
 «Калгари»,
 'Аделаида',
 «Милуоки»,
 «Провиденс»,
 «Джексонвилль»,
 «Шарджа»,
 «Кан Тхо»,
 «Сувон»,
 «Чиангмай»,
 «Доха»,
 «Нэшвилл»,
 «Солт-Лейк-Сити»,
 'Роли',
 'Эдмонтон',
 'Ульсан',
 «Бьен Хоа»,
 'Тунцзин',
 'Ричмонд',
 'Оттава',
 'Гоян',
 'Мемфис',
 «Ту Дык»,
 «Чханвон»,
 «Куанг Ха»,
 'Оклахома Сити',
 'Хартфорд',
 «Хвасу-дон»,
 'Иерусалим',
 «Сонгнам»,
 «Ад Даммам»,
 «Чхонджу»,
 «Пучхон»,
 'Аль Айн',
 'Виннипег',
 «Квебек Сити»,
 'Хюэ',
 'Тан Ан',
 'Ар Райян',
 'Хайфа',
 «Бак Нинь»,
 'Аджман',
 «Накхонратчасима»,
 «Хон Каен»,
 «Хат Яй»,
 'Сумгаит',
 'Ганча',
 'Нукус',
 'Фаргона',
 'Бухара',
 'Карши',
 'Кукон',
 «Туркменабат»,
 'Дашогуз',
 'Маргилон',
 'Батуми',
 «Джизак»,
 'Чирчик',
 'Урганч',
 'Кутаиси',
 'Олмалик',
 'Термиз',
 'Агкабади',
 'Навоий',
 «Рустави»,
 'Гюмри',
 'Ванадзор',
 «Джалал-Абад»,
 'Эчмиадзин',
 «Красноярск»,
 'Воронеж',
 «Пермь»,
 'Одесса',
 'Волгоград',
 «Днепр»,
 «Краснодар»,
 «Донецк»,
 'Тюмень',
 «Саратов»,
 'Львов',
 'Запорожье',
 'Тольятти',
 «Махачкала»,
 «Базальтово»,
 «Кривой Рог»,
 «Гомель»,
 «Севастополь»,
 'Витебск',
 «Пекин»,
 «Калькутта»,
 'Шэньчжэнь',
 'Карачи',
 «Бангалор»,
 «Чэнду»,
 'Тегеран',
 «Рио-де-Жанейро»,
 «Ченнаи»,
 «Сиань»,
 «Лахор»,
 «Чунцин»,
 'Баодин',
 'Линьи',
 «Дунгуань»,
 «Хайдарабад»,
 «Йоханнесбург»,
 «Пуна»,
 «Ахмадабад»,
 'Богота',
 'Сурабая',
 'Гиза',
 «Белу-Оризонти»,
 'Александрия',
 «Кейптаун»,
 «Форталеза»,
 'Медан',
 «Мешхед»,
 «Бразилиа»,
 'Медельин',
 'Дакка',
 'Лагос',
 'Киншаса',
 'Лима',
 'Луанда',
 «Дар-эс-Салам»,
 «Хартум»,
 'Сантьяго',
 «Багдад»,
 'Дуала',
 'Найроби',
 'Рангун',
 'Абиджан',
 «Кабул»,
 'Бамако',
 «Касабланка»,
 'Кумаси',
 'Алжир',
 'Санта-Крус-де-ла Сьерра',
 «Аддис-Абеба»,
Гватемала»,
 'Пхеньян',
 «Гуаякиль»,
 'Могадишо',
 'Дамаск',
 'Антананариву',
 'Каракас
 Гавана',
'Котону'
    """

In [70]:
filtered = []
for line in translated.strip().split('\n'):
    line = line.strip()
    line = line.replace("\"", "").replace('\'', "").replace('\[', '').replace('«', '').replace('»', '').replace('[', '').replace(',', '')
    if len(line) == 0:
        continue
    else:
        filtered.append(line)
filtered

['Алматы',
 'Шымкент',
 'Астана',
 'Караганда',
 'Усть-Каменогорск',
 'Актобе',
 'Тараз',
 'Семей',
 'Павлодар',
 'Туркестан',
 'Кызылорда',
 'Оральный',
 'Костанай',
 'Петропавль',
 'Лондон',
 'Париж',
 'Мадрид',
 'Берлин',
 'Барселона',
 'Афины',
 'Будапешт',
 'Бирмингем',
 'Штутгарт',
 'Рим',
 'Мюнхен',
 'Гамбург',
 'Бухарест',
 'Вена',
 'Стокгольм',
 'Тилбург',
 'Варшава',
 'Валенсия',
 'София',
 'Амстердам',
 'Копенгаген',
 'Хельсинки',
 'Прага',
 'Милан',
 'Порту',
 'Дублин',
 'Брюссель',
 'Белград',
 'Севилья',
 'Кёльн',
 'Осло',
 'Токио',
 'Манила',
 'Сеул',
 'Мехико',
 'Нью-Йорк',
 'Бангкок',
 'Буэнос-Айрес',
 'Стамбул',
 'Хошимин',
 'Осака',
 'Лос-Анджелес',
 'Нагоя',
 'Куала Лумпур',
 'Чикаго',
 'Ханой',
 'Гонконг',
 'Эр-Рияд',
 'Майами',
 'Хьюстон',
 'Даллас',
 'Филадельфия',
 'Торонто',
 'Гвадалахара',
 'Анкара',
 'Монтеррей',
 'Атланта',
 'Вашингтон',
 'Мельбурн',
 'Сидней',
 'Джидда',
 'Бостон',
 'Измир',
 'Феникс',
 'Йокогама',
 'Детройт',
 'Монреаль',
 'Сиэтл',
 'Пусан',
 'Сан-Франциско',
 'Дубай',
 'Сан-Диего',
 'Тайчжун',
 'Кесон-Сити',
 'Инчхон',
 'Бурса',
 'Миннеаполис',
 'Тампа',
 'Бруклин',
 'Денвер',
 'Мекка',
 'Ванкувер',
 'Квинс',
 'Тэгу',
 'Брисбен',
 'Риверсайд',
 'Фукуока',
 'Лас-Вегас',
 'Конья',
 'Балтимор',
 'Перт',
 'Св. Луис',
 'Кордова',
 'Хайфон',
 'Портленд',
 'Сан-Антонио',
 'Тихуана',
 'Саппоро',
 'Сакраменто',
 'Экатепек',
 'Остин',
 'Орландо',
 'Сан-Хосе',
 'Питтсбург',
 'Индианаполис',
 'Манхэттен',
 'Цинциннати',
 'Канзас-Сити',
 'Кливленд',
 'Колумбус',
 'Кавасаки',
 'Кобе',
 'Ташкент',
 'Баку',
 'Бишкек',
 'Тбилиси',
 'Ереван',
 'Ашхабад',
 'Наманган',
 'Андижан',
 'Самарканд',
 'Ош',
 'Москва',
 'Санкт-Петербург',
 'Киев',
 'Минск',
 'Новосибирск',
 'Екатеринбург',
 'Харьков',
 'Казань',
 'Нижний Новгород',
 'Челябинск',
 'Омск',
 'Самара',
 'Ростов',
 'Уфа',
 'Джакарта',
 'Дели',
 'Гуанчжоу',
 'Мумбаи',
 'Шанхай',
 'Сан-Паулу',
 'Каир',
 'Темиртау',
 'Актау',
 'Кокшетау',
 'Экибастуз',
 'Жангаозен',
 'Атырау',
 'Талдыкорган',
 'Рудный',
 'Жезказган',
 'Кентау',
 'Балхаш',
 'Аксу',
 'Сатбаев',
 'Капчагай',
 'Каскеленг',
 'Риддер',
 'Бордо',
 'Малага',
 'Рига',
 'Неаполь',
 'Марсель',
 'Портсмут',
 'Саутгемптон',
 'Турин',
 'Краков',
 'Салоники',
 'Лидс',
 'Бильбао',
 'Франкфурт',
 'Загреб',
 'Ноттингем',
 'Вильнюс',
 'Бристоль',
 'Кишинев',
 'Сарагоса',
 'Вроцлав',
 'Мурсия',
 'Лодзь',
 'Роттердам',
 'Лас-Пальмас',
 'Палермо',
 'Дюссельдорф',
 'Глазго',
 'Лейпциг',
 'Таллинн',
 'Гетеборг',
 'Дортмунд',
 'Эссен',
 'Бремен',
 'Дрезден',
 'Генуя',
 'Пальма',
 'Лиссабон',
 'Гаага',
 'Манчестер',
 'Познань',
 'Ганновер',
 'Санта-Крус',
 'Антверпен',
 'Скопье',
 'Нюрнберг',
 'Лион',
 'Шеффилд',
 'Ливерпуль',
 'Лестер',
 'Тулуза',
 'Дуйсбург',
 'Каэрдидд',
 'Эдинбург',
 'Гданьск',
 'Валлетта',
 'Братислава',
 'Уортинг',
 'Пирей',
 'Цюрих',
 'Авес',
 'Сараево',
 'Тирана',
 'Щецин',
 'Брно',
 'Каунас',
 'Болонья',
 'Новый Сад',
 'Синтра',
 'Сток-он-Трент',
 'Кванджу',
 'Абу-Даби',
 'Тэджон',
 'Бронкс',
 'Киото',
 'Вирджиния Пляж',
 'Шарлотта',
 'Медина',
 'Тель-Авив-Яффо',
 'Калгари',
 'Аделаида',
 'Милуоки',
 'Провиденс',
 'Джексонвилль',
 'Шарджа',
 'Кан Тхо',
 'Сувон',
 'Чиангмай',
 'Доха',
 'Нэшвилл',
 'Солт-Лейк-Сити',
 'Роли',
 'Эдмонтон',
 'Ульсан',
 'Бьен Хоа',
 'Тунцзин',
 'Ричмонд',
 'Оттава',
 'Гоян',
 'Мемфис',
 'Ту Дык',
 'Чханвон',
 'Куанг Ха',
 'Оклахома Сити',
 'Хартфорд',
 'Хвасу-дон',
 'Иерусалим',
 'Сонгнам',
 'Ад Даммам',
 'Чхонджу',
 'Пучхон',
 'Аль Айн',
 'Виннипег',
 'Квебек Сити',
 'Хюэ',
 'Тан Ан',
 'Ар Райян',
 'Хайфа',
 'Бак Нинь',
 'Аджман',
 'Накхонратчасима',
 'Хон Каен',
 'Хат Яй',
 'Сумгаит',
 'Ганча',
 'Нукус',
 'Фаргона',
 'Бухара',
 'Карши',
 'Кукон',
 'Туркменабат',
 'Дашогуз',
 'Маргилон',
 'Батуми',
 'Джизак',
 'Чирчик',
 'Урганч',
 'Кутаиси',
 'Олмалик',
 'Термиз',
 'Агкабади',
 'Навоий',
 'Рустави',
 'Гюмри',
 'Ванадзор',
 'Джалал-Абад',
 'Эчмиадзин',
 'Красноярск',
 'Воронеж',
 'Пермь',
 'Одесса',
 'Волгоград',
 'Днепр',
 'Краснодар',
 'Донецк',
 'Тюмень',
 'Саратов',
 'Львов',
 'Запорожье',
 'Тольятти',
 'Махачкала',
 'Базальтово',
 'Кривой Рог',
 'Гомель',
 'Севастополь',
 'Витебск',
 'Пекин',
 'Калькутта',
 'Шэньчжэнь',
 'Карачи',
 'Бангалор',
 'Чэнду',
 'Тегеран',
 'Рио-де-Жанейро',
 'Ченнаи',
 'Сиань',
 'Лахор',
 'Чунцин',
 'Баодин',
 'Линьи',
 'Дунгуань',
 'Хайдарабад',
 'Йоханнесбург',
 'Пуна',
 'Ахмадабад',
 'Богота',
 'Сурабая',
 'Гиза',
 'Белу-Оризонти',
 'Александрия',
 'Кейптаун',
 'Форталеза',
 'Медан',
 'Мешхед',
 'Бразилиа',
 'Медельин',
 'Дакка',
 'Лагос',
 'Киншаса',
 'Лима',
 'Луанда',
 'Дар-эс-Салам',
 'Хартум',
 'Сантьяго',
 'Багдад',
 'Дуала',
 'Найроби',
 'Рангун',
 'Абиджан',
 'Кабул',
 'Бамако',
 'Касабланка',
 'Кумаси',
 'Алжир',
 'Санта-Крус-де-ла Сьерра',
 'Аддис-Абеба',
 'Гватемала',
 'Пхеньян',
 'Гуаякиль',
 'Могадишо',
 'Дамаск',
 'Антананариву',
 'Каракас',
 'Гавана',
 'Котону']

In [95]:
ru_mapping = {city: translation for translation, city in zip(filtered, cities)} 
index_df['city_ru'] = index_df.city_ascii.map(ru_mapping)
index_df

,city,city_ascii,lat,lng,country,iso2,iso3,population,city_ru
0,Almaty,Almaty,43.2400,76.9150,Kazakhstan,KZ,KAZ,1916822.0,Алматы
1,Shymkent,Shymkent,42.3167,69.5958,Kazakhstan,KZ,KAZ,1184113.0,Шымкент
2,Astana,Astana,51.1472,71.4222,Kazakhstan,KZ,KAZ,1078362.0,Астана
3,Qaraghandy,Qaraghandy,49.8028,73.1056,Kazakhstan,KZ,KAZ,497777.0,Караганда
4,Öskemen,Oskemen,49.9833,82.6167,Kazakhstan,KZ,KAZ,400142.0,Усть-Каменогорск
...,...,...,...,...,...,...,...,...,...
393,Antananarivo,Antananarivo,-18.9100,47.5250,Madagascar,MG,MDG,2300000.0,Антананариву
394,Caracas,Caracas,10.4806,-66.9036,Venezuela,VE,VEN,2245744.0,Каракас
395,Havana,Havana,23.1367,-82.3589,Cuba,CU,CUB,2089532.0,Гавана
396,Santiago,Santiago,19.4572,-70.6889,Dominican Republic,DO,DOM,1343423.0,Сантьяго
397,Cotonou,Cotonou,6.3667,2.4333,Benin,BJ,BEN,679012.0,Котону

In [102]:
ru_mapping_countries = {city: translation for city, translation in zip(index_df.country.unique(), filtered_countries)} 
index_df['country_ru'] = index_df.country.map(ru_mapping_countries)
index_df

,city,city_ascii,lat,lng,country,iso2,iso3,population,city_ru,country_ru
0,Almaty,Almaty,43.2400,76.9150,Kazakhstan,KZ,KAZ,1916822.0,Алматы,Казахстан
1,Shymkent,Shymkent,42.3167,69.5958,Kazakhstan,KZ,KAZ,1184113.0,Шымкент,Казахстан
2,Astana,Astana,51.1472,71.4222,Kazakhstan,KZ,KAZ,1078362.0,Астана,Казахстан
3,Qaraghandy,Qaraghandy,49.8028,73.1056,Kazakhstan,KZ,KAZ,497777.0,Караганда,Казахстан
4,Öskemen,Oskemen,49.9833,82.6167,Kazakhstan,KZ,KAZ,400142.0,Усть-Каменогорск,Казахстан
...,...,...,...,...,...,...,...,...,...,...
393,Antananarivo,Antananarivo,-18.9100,47.5250,Madagascar,MG,MDG,2300000.0,Антананариву,Мадагаскар
394,Caracas,Caracas,10.4806,-66.9036,Venezuela,VE,VEN,2245744.0,Каракас,Венесуэла
395,Havana,Havana,23.1367,-82.3589,Cuba,CU,CUB,2089532.0,Гавана,Куба
396,Santiago,Santiago,19.4572,-70.6889,Dominican Republic,DO,DOM,1343423.0,Сантьяго,Доминиканская Республика
397,Cotonou,Cotonou,6.3667,2.4333,Benin,BJ,BEN,679012.0,Котону,Бенин

In [98]:
translated = """
'Казахстан', 'Великобритания', 'Франция', 'Испания', 'Германия',
'Греция', 'Венгрия', 'Италия', 'Румыния', 'Австрия', 'Швеция',
'Нидерланды', 'Польша', 'Болгария', 'Дания', 'Финляндия',
'Чешская Республика', 'Португалия', 'Ирландия', 'Бельгия', 'Сербия',
'Норвегия', 'Япония', 'Филиппины', 'Южная Корея', 'Мексика',
'США', 'Таиланд', 'Аргентина', 'Турция', 'Вьетнам',
'Малайзия', 'Гонконг Kong, 'Саудовская Аравия', 'Канада', 'Австралия',
'Объединенные Арабские Эмираты', 'Тайвань', 'Узбекистан', 'Азербайджан',
'Киргизия', 'Грузия', 'Армения', 'Туркменистан', 'Россия',
'Украина', 'Беларусь', 'Индонезия', 'Индия', 'Китай', 'Бразилия',
'Египет', 'Латвия', 'Хорватия', 'Литва', 'Молдова', 'Эстония',
'Северная Македония', 'Мальта', 'Словакия', 'Швейцария',
'Босния и Герцеговина', 'Албания', «Израиль», «Катар», «Пакистан»,
«Иран», «Южная Африка», «Колумбия», «Бангладеш», «Нигерия»,
«Конго (Киншаса)», «Перу», «Ангола», «Танзания», «Судан», «Чили»,
«Ирак», «Камерун», «Кения», «Бирма», «Кот-д’Ивуар»,
«Афганистан», «Мали», «Марокко», «Гана», «Алжир», «Боливия»,
«Эфиопия», «Гватемала», «Северная Корея», «Эквадор», «Сомали»,
«Сирия», 'Мадагаскар', 'Венесуэла', 'Куба', 'Доминиканская Республика',
'Бенин'
"""
filtered_countries = []
for line in translated.strip().split(','):
    line = line.strip()
    line = line.replace("\"", "").replace('\'', "").replace('\[', '').replace('«', '').replace('»', '').replace('[', '').replace(',', '')
    if len(line) == 0:
        continue
    else:
        filtered_countries.append(line)
filtered_countries

['Казахстан',
 'Великобритания',
 'Франция',
 'Испания',
 'Германия',
 'Греция',
 'Венгрия',
 'Италия',
 'Румыния',
 'Австрия',
 'Швеция',
 'Нидерланды',
 'Польша',
 'Болгария',
 'Дания',
 'Финляндия',
 'Чешская Республика',
 'Португалия',
 'Ирландия',
 'Бельгия',
 'Сербия',
 'Норвегия',
 'Япония',
 'Филиппины',
 'Южная Корея',
 'Мексика',
 'США',
 'Таиланд',
 'Аргентина',
 'Турция',
 'Вьетнам',
 'Малайзия',
 'Гонконг Kong',
 'Саудовская Аравия',
 'Канада',
 'Австралия',
 'Объединенные Арабские Эмираты',
 'Тайвань',
 'Узбекистан',
 'Азербайджан',
 'Киргизия',
 'Грузия',
 'Армения',
 'Туркменистан',
 'Россия',
 'Украина',
 'Беларусь',
 'Индонезия',
 'Индия',
 'Китай',
 'Бразилия',
 'Египет',
 'Латвия',
 'Хорватия',
 'Литва',
 'Молдова',
 'Эстония',
 'Северная Македония',
 'Мальта',
 'Словакия',
 'Швейцария',
 'Босния и Герцеговина',
 'Албания',
 'Израиль',
 'Катар',
 'Пакистан',
 'Иран',
 'Южная Африка',
 'Колумбия',
 'Бангладеш',
 'Нигерия',
 'Конго (Киншаса)',
 'Перу',
 'Ангола',
 'Танзания',
 'Судан',
 'Чили',
 'Ирак',
 'Камерун',
 'Кения',
 'Бирма',
 'Кот-д’Ивуар',
 'Афганистан',
 'Мали',
 'Марокко',
 'Гана',
 'Алжир',
 'Боливия',
 'Эфиопия',
 'Гватемала',
 'Северная Корея',
 'Эквадор',
 'Сомали',
 'Сирия',
 'Мадагаскар',
 'Венесуэла',
 'Куба',
 'Доминиканская Республика',
 'Бенин']

In [112]:
index_df['population'] = index_df['population'].astype(int) // 1000 * 1000
index_df

,city,city_ascii,lat,lng,country,iso2,iso3,population,city_ru,country_ru
0,Almaty,Almaty,43.2400,76.9150,Kazakhstan,KZ,KAZ,1916000,Алматы,Казахстан
1,Shymkent,Shymkent,42.3167,69.5958,Kazakhstan,KZ,KAZ,1184000,Шымкент,Казахстан
2,Astana,Astana,51.1472,71.4222,Kazakhstan,KZ,KAZ,1078000,Астана,Казахстан
3,Qaraghandy,Qaraghandy,49.8028,73.1056,Kazakhstan,KZ,KAZ,497000,Караганда,Казахстан
4,Öskemen,Oskemen,49.9833,82.6167,Kazakhstan,KZ,KAZ,400000,Усть-Каменогорск,Казахстан
...,...,...,...,...,...,...,...,...,...,...
393,Antananarivo,Antananarivo,-18.9100,47.5250,Madagascar,MG,MDG,2300000,Антананариву,Мадагаскар
394,Caracas,Caracas,10.4806,-66.9036,Venezuela,VE,VEN,2245000,Каракас,Венесуэла
395,Havana,Havana,23.1367,-82.3589,Cuba,CU,CUB,2089000,Гавана,Куба
396,Santiago,Santiago,19.4572,-70.6889,Dominican Republic,DO,DOM,1343000,Сантьяго,Доминиканская Республика
397,Cotonou,Cotonou,6.3667,2.4333,Benin,BJ,BEN,679000,Котону,Бенин

In [117]:
index_df.reset_index(names='priority').to_csv('cities_index_with_ru.csv', index=False)

In [75]:
index_df.city_ascii.tolist()

['Almaty',
 'Shymkent',
 'Astana',
 'Qaraghandy',
 'Oskemen',
 'Aqtobe',
 'Taraz',
 'Semey',
 'Pavlodar',
 'Turkistan',
 'Qyzylorda',
 'Oral',
 'Qostanay',
 'Petropavl',
 'London',
 'Paris',
 'Madrid',
 'Berlin',
 'Barcelona',
 'Athens',
 'Budapest',
 'Birmingham',
 'Stuttgart',
 'Rome',
 'Munich',
 'Hamburg',
 'Bucharest',
 'Vienna',
 'Stockholm',
 'Tilburg',
 'Warsaw',
 'Valencia',
 'Sofia',
 'Amsterdam',
 'Copenhagen',
 'Helsinki',
 'Prague',
 'Milan',
 'Porto',
 'Dublin',
 'Brussels',
 'Belgrade',
 'Sevilla',
 'Cologne',
 'Oslo',
 'Tokyo',
 'Manila',
 'Seoul',
 'Mexico City',
 'New York',
 'Bangkok',
 'Buenos Aires',
 'Istanbul',
 'Ho Chi Minh City',
 'Osaka',
 'Los Angeles',
 'Nagoya',
 'Kuala Lumpur',
 'Chicago',
 'Hanoi',
 'Hong Kong',
 'Riyadh',
 'Miami',
 'Houston',
 'Dallas',
 'Philadelphia',
 'Toronto',
 'Guadalajara',
 'Ankara',
 'Monterrey',
 'Atlanta',
 'Washington',
 'Melbourne',
 'Sydney',
 'Jeddah',
 'Boston',
 'Izmir',
 'Phoenix',
 'Yokohama',
 'Detroit',
 'Montreal',
 'Seattle',
 'Busan',
 'San Francisco',
 'Dubai',
 'San Diego',
 'Taichung',
 'Quezon City',
 'Incheon',
 'Bursa',
 'Minneapolis',
 'Tampa',
 'Brooklyn',
 'Denver',
 'Mecca',
 'Vancouver',
 'Queens',
 'Daegu',
 'Brisbane',
 'Riverside',
 'Fukuoka',
 'Las Vegas',
 'Konya',
 'Baltimore',
 'Perth',
 'St. Louis',
 'Cordoba',
 'Haiphong',
 'Portland',
 'San Antonio',
 'Tijuana',
 'Sapporo',
 'Sacramento',
 'Ecatepec',
 'Austin',
 'Orlando',
 'San Jose',
 'Pittsburgh',
 'Indianapolis',
 'Manhattan',
 'Cincinnati',
 'Kansas City',
 'Cleveland',
 'Columbus',
 'Kawasaki',
 'Kobe',
 'Tashkent',
 'Baku',
 'Bishkek',
 'Tbilisi',
 'Yerevan',
 'Ashgabat',
 'Namangan',
 'Andijon',
 'Samarkand',
 'Osh',
 'Moscow',
 'Saint Petersburg',
 'Kyiv',
 'Minsk',
 'Novosibirsk',
 'Yekaterinburg',
 'Kharkiv',
 'Kazan',
 'Nizhniy Novgorod',
 'Chelyabinsk',
 'Omsk',
 'Samara',
 'Rostov',
 'Ufa',
 'Jakarta',
 'Delhi',
 'Guangzhou',
 'Mumbai',
 'Shanghai',
 'Sao Paulo',
 'Cairo',
 'Temirtau',
 'Aqtau',
 'Kokshetau',
 'Ekibastuz',
 'Zhangaozen',
 'Atyrau',
 'Taldyqorghan',
 'Rudnyy',
 'Zhezqazghan',
 'Kentau',
 'Balqash',
 'Aqsu',
 'Satbayev',
 'Kapchagay',
 'Qaskeleng',
 'Ridder',
 'Bordeaux',
 'Malaga',
 'Riga',
 'Naples',
 'Marseille',
 'Portsmouth',
 'Southampton',
 'Turin',
 'Krakow',
 'Thessaloniki',
 'Leeds',
 'Bilbao',
 'Frankfurt',
 'Zagreb',
 'Nottingham',
 'Vilnius',
 'Bristol',
 'Chisinau',
 'Zaragoza',
 'Wroclaw',
 'Murcia',
 'Lodz',
 'Rotterdam',
 'Las Palmas',
 'Palermo',
 'Dusseldorf',
 'Glasgow',
 'Leipzig',
 'Tallinn',
 'Gothenburg',
 'Dortmund',
 'Essen',
 'Bremen',
 'Dresden',
 'Genoa',
 'Palma',
 'Lisbon',
 'The Hague',
 'Manchester',
 'Poznan',
 'Hannover',
 'Santa Cruz',
 'Antwerp',
 'Skopje',
 'Nuremberg',
 'Lyon',
 'Sheffield',
 'Liverpool',
 'Leicester',
 'Toulouse',
 'Duisburg',
 'Caerdydd',
 'Edinburgh',
 'Gdansk',
 'Valletta',
 'Bratislava',
 'Worthing',
 'Piraeus',
 'Zurich',
 'Aves',
 'Sarajevo',
 'Tirana',
 'Szczecin',
 'Brno',
 'Kaunas',
 'Bologna',
 'Novi Sad',
 'Sintra',
 'Stoke-on-Trent',
 'Gwangju',
 'Abu Dhabi',
 'Daejeon',
 'Bronx',
 'Kyoto',
 'Virginia Beach',
 'Charlotte',
 'Medina',
 'Tel Aviv-Yafo',
 'Calgary',
 'Adelaide',
 'Milwaukee',
 'Providence',
 'Jacksonville',
 'Sharjah',
 'Can Tho',
 'Suwon',
 'Chiang Mai',
 'Doha',
 'Nashville',
 'Salt Lake City',
 'Raleigh',
 'Edmonton',
 'Ulsan',
 'Bien Hoa',
 'Tongjin',
 'Richmond',
 'Ottawa',
 'Goyang',
 'Memphis',
 'Thu Duc',
 'Changwon',
 'Quang Ha',
 'Oklahoma City',
 'Hartford',
 'Hwasu-dong',
 'Jerusalem',
 'Songnam',
 'Ad Dammam',
 'Cheongju',
 'Bucheon',
 'Al `Ayn',
 'Winnipeg',
 'Quebec City',
 'Hue',
 'Tan An',
 'Ar Rayyan',
 'Haifa',
 'Bac Ninh',
 '`Ajman',
 'Nakhon Ratchasima',
 'Khon Kaen',
 'Hat Yai',
 'Sumqayit',
 'Ganca',
 'Nukus',
 'Farg`ona',
 'Bukhara',
 'Qarshi',
 'Qo`qon',
 'Turkmenabat',
 'Dasoguz',
 'Marg`ilon',
 'Batumi',
 'Jizzax',
 'Chirchiq',
 'Urganch',
 'Kutaisi',
 'Olmaliq',
 'Termiz',
 'Agcabadi',
 'Navoiy',
 'Rustavi',
 'Gyumri',
 'Vanadzor',
 'Jalal-Abad',
 'Ejmiatsin',
 'Krasnoyarsk',
 'Voronezh',
 'Perm',
 'Odesa',
 'Volgograd',
 'Dnipro',
 'Krasnodar',
 'Donetsk',
 'Tyumen',
 'Saratov',
 'Lviv',
 'Zaporizhzhia',
 'Tolyatti',
 'Makhachkala',
 "Bazal'tove",
 'Kryvyi Rih',
 "Homyel'",
 'Sevastopol',
 'Vitsyebsk',
 'Beijing',
 'Kolkata',
 'Shenzhen',
 'Karachi',
 'Bangalore',
 'Chengdu',
 'Tehran',
 'Rio de Janeiro',
 'Chennai',
 "Xi'an",
 'Lahore',
 'Chongqing',
 'Baoding',
 'Linyi',
 'Dongguan',
 'Hyderabad',
 'Johannesburg',
 'Pune',
 'Ahmedabad',
 'Bogota',
 'Surabaya',
 'Giza',
 'Belo Horizonte',
 'Alexandria',
 'Cape Town',
 'Fortaleza',
 'Medan',
 'Mashhad',
 'Brasilia',
 'Medellin',
 'Dhaka',
 'Lagos',
 'Kinshasa',
 'Lima',
 'Luanda',
 'Dar es Salaam',
 'Khartoum',
 'Santiago',
 'Baghdad',
 'Douala',
 'Nairobi',
 'Rangoon',
 'Abidjan',
 'Kabul',
 'Bamako',
 'Casablanca',
 'Kumasi',
 'Algiers',
 'Santa Cruz de la Sierra',
 'Addis Ababa',
 'Guatemala City',
 'Pyongyang',
 'Guayaquil',
 'Mogadishu',
 'Damascus',
 'Antananarivo',
 'Caracas',
 'Havana',
 'Santiago',
 'Cotonou']

In [200]:
source[source.country == 'Hong Kong'].head(20)

,city,city_ascii,lat,lng,country,iso2,iso3,admin_name,capital,population,id,in_europe
67,Hong Kong,Hong Kong,22.3000,114.2000,Hong Kong,HK,HKG,NaN,primary,7450000.0,1344982653,False
393,Kowloon,Kowloon,22.3167,114.1833,Hong Kong,HK,HKG,NaN,NaN,2108419.0,1344538284,False
1170,Sha Tin,Sha Tin,22.3802,114.1898,Hong Kong,HK,HKG,NaN,NaN,640000.0,1344745541,False
1717,Kowloon City,Kowloon City,22.3282,114.1916,Hong Kong,HK,HKG,NaN,NaN,418732.0,1344000061,False
1773,Sham Shui Po,Sham Shui Po,22.3307,114.1622,Hong Kong,HK,HKG,NaN,NaN,405869.0,1344000058,False
2401,Tin Shui Wai,Tin Shui Wai,22.4600,114.0020,Hong Kong,HK,HKG,NaN,NaN,286232.0,1344389641,False
2844,Central District,Central District,22.2867,114.1550,Hong Kong,HK,HKG,NaN,NaN,235953.0,1344000057,False
3430,Tsing Yi Town,Tsing Yi Town,22.3456,114.1000,Hong Kong,HK,HKG,NaN,NaN,191500.0,1344057832,False
4795,Lam Tin,Lam Tin,22.3094,114.2361,Hong Kong,HK,HKG,NaN,NaN,131000.0,1344141583,False
5378,San Tung Chung Hang,San Tung Chung Hang,22.2869,113.9436,Hong Kong,HK,HKG,NaN,NaN,116022.0,1344851698,False
10566,Kennedy Town,Kennedy Town,22.2800,114.1250,Hong Kong,HK,HKG,NaN,NaN,54000.0,1344000050,False
14114,Kwai Chung,Kwai Chung,22.3674,114.1273,Hong Kong,HK,HKG,NaN,NaN,38674.0,1344773013,False
22962,Pak Tin Pa,Pak Tin Pa,22.3364,114.1667,Hong Kong,HK,HKG,NaN,NaN,21902.0,1344000101,False
24966,Cheung Chau,Cheung Chau,22.2106,114.0289,Hong Kong,HK,HKG,NaN,NaN,19769.0,1344565945,False
26326,Choi Hung,Choi Hung,22.3350,114.2067,Hong Kong,HK,HKG,NaN,NaN,18435.0,1344000072,False
27780,Shek Tong Tsui,Shek Tong Tsui,22.2871,114.1357,Hong Kong,HK,HKG,NaN,NaN,17170.0,1344000053,False
27852,Wang Tau Hom,Wang Tau Hom,22.3408,114.1871,Hong Kong,HK,HKG,NaN,NaN,17116.0,1344000105,False
28506,Shek Wai Kok,Shek Wai Kok,22.3753,114.1237,Hong Kong,HK,HKG,NaN,NaN,16605.0,1344833550,False
29908,Tung Tau Tsuen,Tung Tau Tsuen,22.3334,114.1924,Hong Kong,HK,HKG,NaN,NaN,15562.0,1344000062,False
31496,Sha Kok Mei,Sha Kok Mei,22.3784,114.1941,Hong Kong,HK,HKG,NaN,NaN,14522.0,1344631625,False

In [ ]:
european_cities = source[(source.in_europe)].head(100)
european_cities

,city,city_ascii,lat,lng,country,iso2,iso3,admin_name,capital,population,id,in_europe
35,London,London,51.5072,-0.1275,United Kingdom,GB,GBR,"London, City of",primary,11262000.0,1826645935,True
36,Paris,Paris,48.8567,2.3522,France,FR,FRA,Île-de-France,primary,11060000.0,1250015082,True
84,Madrid,Madrid,40.4169,-3.7033,Spain,ES,ESP,Madrid,primary,6211000.0,1724616994,True
134,Berlin,Berlin,52.5200,13.4050,Germany,DE,DEU,Berlin,primary,4890363.0,1276451290,True
139,Barcelona,Barcelona,41.3828,2.1769,Spain,ES,ESP,Catalonia,admin,4800000.0,1724594040,True
...,...,...,...,...,...,...,...,...,...,...,...,...
1523,Gdańsk,Gdansk,54.3475,18.6453,Poland,PL,POL,Pomorskie,admin,486022.0,1616406372,True
1524,Sevastopol,Sevastopol,44.6050,33.5225,Ukraine,UA,UKR,"Sevastopol, Misto",admin,485386.0,1804806030,True
1535,Valletta,Valletta,35.8983,14.5125,Malta,MT,MLT,Valletta,primary,480134.0,1470574399,True
1549,Bratislava,Bratislava,48.1439,17.1097,Slovakia,SK,SVK,Bratislava,primary,475503.0,1703195001,True
1552,Worthing,Worthing,50.8147,-0.3714,United Kingdom,GB,GBR,West Sussex,NaN,474485.0,1826936965,True

,city,city_ascii,lat,lng,country,iso2,iso3,admin_name,capital,population,id,in_europe
3,Guangzhou,Guangzhou,23.1300,113.2600,China,CN,CHN,Guangdong,admin,26940000.0,1156237133,False
6,Shanghai,Shanghai,31.2286,121.4747,China,CN,CHN,Shanghai,admin,24073000.0,1156073548,False
13,Beijing,Beijing,39.9067,116.3975,China,CN,CHN,Beijing,primary,18522000.0,1156228865,False
16,Shenzhen,Shenzhen,22.5415,114.0596,China,CN,CHN,Guangdong,minor,17619000.0,1156158707,False
25,Chengdu,Chengdu,30.6600,104.0633,China,CN,CHN,Sichuan,admin,14645000.0,1156421555,False
30,Xi’an,Xi'an,34.2611,108.9422,China,CN,CHN,Shaanxi,admin,12328000.0,1156244079,False
32,Chongqing,Chongqing,29.5637,106.5504,China,CN,CHN,Chongqing,admin,12135000.0,1156936556,False
34,Baoding,Baoding,38.8740,115.4640,China,CN,CHN,Hebei,minor,11544036.0,1156256829,False
37,Linyi,Linyi,35.1038,118.3564,China,CN,CHN,Shandong,NaN,11018365.0,1156086320,False
38,Dongguan,Dongguan,23.0210,113.7520,China,CN,CHN,Guangdong,minor,10646000.0,1156478242,False
40,Tianjin,Tianjin,39.1336,117.2054,China,CN,CHN,Tianjin,admin,10368000.0,1156174046,False
42,Wuhan,Wuhan,30.5934,114.3046,China,CN,CHN,Hubei,admin,10251000.0,1156117184,False
43,Nanyang,Nanyang,32.9987,112.5292,China,CN,CHN,Henan,NaN,9713112.0,1156192287,False
44,Hangzhou,Hangzhou,30.2670,120.1530,China,CN,CHN,Zhejiang,admin,9523000.0,1156275243,False
45,Foshan,Foshan,23.0214,113.1216,China,CN,CHN,Guangdong,minor,9498863.0,1156738403,False
47,Tongshan,Tongshan,34.2040,117.2840,China,CN,CHN,Jiangsu,minor,9083790.0,1156241678,False
49,Zhoukou,Zhoukou,33.6250,114.6418,China,CN,CHN,Henan,minor,9026015.0,1156272098,False
50,Ganzhou,Ganzhou,25.8310,114.9330,China,CN,CHN,Jiangxi,minor,8970014.0,1156832475,False
52,Heze,Heze,35.2343,115.4796,China,CN,CHN,Shandong,minor,8795939.0,1156225008,False
53,Quanzhou,Quanzhou,24.8744,118.6757,China,CN,CHN,Fujian,minor,8782285.0,1156829655,False

In [39]:
source[source['in_europe']].head(100)

,city,city_ascii,lat,lng,country,iso2,iso3,admin_name,capital,population,id,in_europe
35,London,London,51.5072,-0.1275,United Kingdom,GB,GBR,"London, City of",primary,11262000.0,1826645935,True
36,Paris,Paris,48.8567,2.3522,France,FR,FRA,Île-de-France,primary,11060000.0,1250015082,True
84,Madrid,Madrid,40.4169,-3.7033,Spain,ES,ESP,Madrid,primary,6211000.0,1724616994,True
134,Berlin,Berlin,52.5200,13.4050,Germany,DE,DEU,Berlin,primary,4890363.0,1276451290,True
139,Barcelona,Barcelona,41.3828,2.1769,Spain,ES,ESP,Catalonia,admin,4800000.0,1724594040,True
...,...,...,...,...,...,...,...,...,...,...,...,...
1523,Gdańsk,Gdansk,54.3475,18.6453,Poland,PL,POL,Pomorskie,admin,486022.0,1616406372,True
1524,Sevastopol,Sevastopol,44.6050,33.5225,Ukraine,UA,UKR,"Sevastopol, Misto",admin,485386.0,1804806030,True
1535,Valletta,Valletta,35.8983,14.5125,Malta,MT,MLT,Valletta,primary,480134.0,1470574399,True
1549,Bratislava,Bratislava,48.1439,17.1097,Slovakia,SK,SVK,Bratislava,primary,475503.0,1703195001,True
1552,Worthing,Worthing,50.8147,-0.3714,United Kingdom,GB,GBR,West Sussex,NaN,474485.0,1826936965,True

In [106]:
source.groupby('country').population.sum().astype(int).sort_values(ascending=False).iloc[50:80].to_dict()

{'Somalia': 14899250,
 'Bolivia': 13438092,
 'Mali': 12877907,
 'Kenya': 12856180,
 'Ethiopia': 12717539,
 'Portugal': 12702173,
 'Syria': 12654371,
 'Hong Kong': 12253254,
 'Cuba': 11882723,
 'Uzbekistan': 11707421,
 'Kazakhstan': 11690063,
 'Belgium': 11276682,
 'Korea, North': 10631804,
 'Greece': 10588342,
 'Afghanistan': 10381124,
 'Romania': 10315088,
 'Benin': 10306467,
 'Ecuador': 10168782,
 'Dominican Republic': 10144495,
 'Hungary': 8290892,
 'Haiti': 7968616,
 'Uganda': 7851132,
 'Israel': 7765242,
 'United Arab Emirates': 7721368,
 'Jordan': 7648777,
 'Sweden': 7583356,
 'Tunisia': 7568765,
 'Honduras': 6990412,
 'Yemen': 6946616,
 'Belarus': 6814494}

In [132]:
source[source.country == 'Belarus'].head(20)

,city,city_ascii,lat,lng,country,iso2,iso3,admin_name,capital,population,id,in_europe
418,Minsk,Minsk,53.9000,27.5667,Belarus,BY,BLR,Minsk,primary,1995471.0,1112348503,False
1469,Homyel’,Homyel',52.4453,30.9842,Belarus,BY,BLR,Homyel’skaya Voblasts’,admin,501802.0,1112580227,False
1954,Vitsyebsk,Vitsyebsk,55.1917,30.2056,Belarus,BY,BLR,Vitsyebskaya Voblasts’,admin,359148.0,1112480679,False
1957,Hrodna,Hrodna,53.6667,23.8333,Belarus,BY,BLR,Hrodzyenskaya Voblasts’,admin,358717.0,1112187197,False
1984,Mahilyow,Mahilyow,53.9167,30.3500,Belarus,BY,BLR,Mahilyowskaya Voblasts’,admin,353338.0,1112518993,False
2051,Brest,Brest,52.1347,23.6569,Belarus,BY,BLR,Brestskaya Voblasts’,admin,342461.0,1112896927,False
3180,Babruysk,Babruysk,53.1500,29.2333,Belarus,BY,BLR,Mahilyowskaya Voblasts’,minor,208611.0,1112573808,False
3755,Baranavichy,Baranavichy,53.1333,26.0167,Belarus,BY,BLR,Brestskaya Voblasts’,minor,172150.0,1112421165,False
4121,Horad Barysaw,Horad Barysaw,54.2279,28.5050,Belarus,BY,BLR,Minskaya Voblasts’,minor,155389.0,1112659163,False
5019,Pinsk,Pinsk,52.1153,26.1031,Belarus,BY,BLR,Brestskaya Voblasts’,minor,124613.0,1112209279,False
5869,Mazyr,Mazyr,52.0500,29.2500,Belarus,BY,BLR,Homyel’skaya Voblasts’,minor,105321.0,1112704173,False
5940,Lida,Lida,53.8956,25.2958,Belarus,BY,BLR,Hrodzyenskaya Voblasts’,NaN,103915.0,1112110662,False
5952,Orsha,Orsha,54.5092,30.4258,Belarus,BY,BLR,Vitsyebskaya Voblasts’,minor,103658.0,1112188007,False
6238,Salihorsk,Salihorsk,52.8000,27.5333,Belarus,BY,BLR,Minskaya Voblasts’,minor,98590.0,1112250470,False
6356,Navapolatsk,Navapolatsk,55.5333,28.6500,Belarus,BY,BLR,Vitsyebskaya Voblasts’,NaN,96320.0,1112965860,False
6782,Maladzyechna,Maladzyechna,54.3208,26.8572,Belarus,BY,BLR,Minskaya Voblasts’,minor,89268.0,1112822882,False
7447,Polatsk,Polatsk,55.4833,28.8000,Belarus,BY,BLR,Vitsyebskaya Voblasts’,minor,79960.0,1112068992,False
7703,Zhlobin,Zhlobin,52.9000,30.0333,Belarus,BY,BLR,Homyel’skaya Voblasts’,minor,77049.0,1112494264,False
8929,Rechytsa,Rechytsa,52.3639,30.3947,Belarus,BY,BLR,Homyel’skaya Voblasts’,minor,65423.0,1112587997,False
9099,Horad Zhodzina,Horad Zhodzina,54.1000,28.3500,Belarus,BY,BLR,Minskaya Voblasts’,minor,64000.0,1112402017,False

In [111]:
global_countries = {
    'China': 10,
    'India': 8,
    'United States': 50,
    'Brazil': 5,
    'Japan': 9,
    'Philippines': 2,
    'Mexico': 5,
    'Turkey': 10,
    'Indonesia': 3,
    'Pakistan': 2,
    'Iran': 2,
    'Korea, South': 15,
    'Egypt': 3,
    'Vietnam': 20,
    'Colombia': 2,
    'Argentina': 2,
    'Canada': 8,
    'Ukraine': 20,
    'Saudi Arabia': 5,
    'Australia': 5,
    'Taiwan': 1,
    'United Arab Emirates': 5,
    'Israel': 3
}
for country, n_cities in global_countries.items():
    sample = source[source.country == country]
    print(sample.head(n_cities))

         city city_ascii      lat       lng country iso2 iso3 admin_name  \
3   Guangzhou  Guangzhou  23.1300  113.2600   China   CN  CHN  Guangdong
6    Shanghai   Shanghai  31.2286  121.4747   China   CN  CHN   Shanghai
13    Beijing    Beijing  39.9067  116.3975   China   CN  CHN    Beijing
16   Shenzhen   Shenzhen  22.5415  114.0596   China   CN  CHN  Guangdong
25    Chengdu    Chengdu  30.6600  104.0633   China   CN  CHN    Sichuan
30      Xi’an      Xi'an  34.2611  108.9422   China   CN  CHN    Shaanxi
32  Chongqing  Chongqing  29.5637  106.5504   China   CN  CHN  Chongqing
34    Baoding    Baoding  38.8740  115.4640   China   CN  CHN      Hebei
37      Linyi      Linyi  35.1038  118.3564   China   CN  CHN   Shandong
38   Dongguan   Dongguan  23.0210  113.7520   China   CN  CHN  Guangdong

    capital  population          id  in_europe
3     admin  26940000.0  1156237133      False
6     admin  24073000.0  1156073548      False
13  primary  18522000.0  1156228865      False
16    minor  17619000.0  1156158707      False
25    admin  14645000.0  1156421555      False
30    admin  12328000.0  1156244079      False
32    admin  12135000.0  1156936556      False
34    minor  11544036.0  1156256829      False
37      NaN  11018365.0  1156086320      False
38    minor  10646000.0  1156478242      False
         city city_ascii      lat      lng country iso2 iso3   admin_name  \
2       Delhi      Delhi  28.6100  77.2300   India   IN  IND        Delhi
4      Mumbai     Mumbai  19.0761  72.8775   India   IN  IND  Mahārāshtra
14    Kolkāta    Kolkata  22.5675  88.3700   India   IN  IND  West Bengal
22  Bangalore  Bangalore  12.9789  77.5917   India   IN  IND    Karnātaka
29    Chennai    Chennai  13.0825  80.2750   India   IN  IND   Tamil Nādu
39  Hyderābād  Hyderabad  17.3617  78.4747   India   IN  IND    Telangāna
59       Pune       Pune  18.5203  73.8567   India   IN  IND  Mahārāshtra
61  Ahmedabad  Ahmedabad  23.0225  72.5714   India   IN  IND      Gujarāt

   capital  population          id  in_europe
2    admin  32226000.0  1356872604      False
4    admin  24973000.0  1356226629      False
14   admin  18502000.0  1356060520      False
22   admin  15386000.0  1356410365      False
29   admin  12395000.0  1356374944      False
39   admin  10494000.0  1356871768      False
59     NaN   8231000.0  1356081074      False
61   minor   8009000.0  1356304381      False
               city      city_ascii      lat       lng        country iso2  \
11         New York        New York  40.6943  -73.9249  United States   US
33      Los Angeles     Los Angeles  34.1141 -118.4068  United States   US
55          Chicago         Chicago  41.8375  -87.6866  United States   US
88            Miami           Miami  25.7840  -80.2101  United States   US
90          Houston         Houston  29.7860  -95.3885  United States   US
94           Dallas          Dallas  32.7935  -96.7667  United States   US
100    Philadelphia    Philadelphia  40.0077  -75.1339  United States   US
122         Atlanta         Atlanta  33.7628  -84.4220  United States   US
123      Washington      Washington  38.9047  -77.0163  United States   US
161          Boston          Boston  42.3188  -71.0852  United States   US
179         Phoenix         Phoenix  33.5722 -112.0892  United States   US
198         Detroit         Detroit  42.3834  -83.1024  United States   US
212         Seattle         Seattle  47.6211 -122.3244  United States   US
225   San Francisco   San Francisco  37.7558 -122.4449  United States   US
252       San Diego       San Diego  32.8313 -117.1222  United States   US
272     Minneapolis     Minneapolis  44.9635  -93.2678  United States   US
279           Tampa           Tampa  27.9945  -82.4447  United States   US
288        Brooklyn        Brooklyn  40.6501  -73.9496  United States   US
296          Denver          Denver  39.7620 -104.8758  United States   US
345          Queens          Queens  40.7498  -73.7976  United States   US
356       Riverside       Riverside  33.9381 -117.3949  United States   US
369       Las Vegas       Las Vegas  36.2333 -115.2654  United States   US
377       Baltimore       Baltimore  39.3051  -76.6144  United States   US
387       St. Louis       St. Louis  38.6359  -90.2451  United States   US
399        Portland        Portland  45.5371 -122.6500  United States   US
408     San Antonio     San Antonio  29.4632  -98.5238  United States   US
424      Sacramento      Sacramento  38.5677 -121.4685  United States   US
429          Austin          Austin  30.3005  -97.7522  United States   US
434         Orlando         Orlando  28.4773  -81.3370  United States   US
454        San Jose        San Jose  37.3012 -121.8480  United States   US
458      Pittsburgh      Pittsburgh  40.4397  -79.9763  United States   US
462    Indianapolis    Indianapolis  39.7771  -86.1458  United States   US
467       Manhattan       Manhattan  40.7834  -73.9662  United States   US
468      Cincinnati      Cincinnati  39.1413  -84.5060  United States   US
469     Kansas City     Kansas City  39.1238  -94.5541  United States   US
473       Cleveland       Cleveland  41.4764  -81.6805  United States   US
496        Columbus        Columbus  39.9862  -82.9855  United States   US
532           Bronx           Bronx  40.8501  -73.8662  United States   US
541  Virginia Beach  Virginia Beach  36.7335  -76.0435  United States   US
544       Charlotte       Charlotte  35.2083  -80.8303  United States   US
592       Milwaukee       Milwaukee  43.0642  -87.9675  United States   US
593      Providence      Providence  41.8230  -71.4187  United States   US
594    Jacksonville    Jacksonville  30.3322  -81.6749  United States   US
650       Nashville       Nashville  36.1715  -86.7842  United States   US
654  Salt Lake City  Salt Lake City  40.7776 -111.9311  United States   US
660         Raleigh         Raleigh  35.8324  -78.6429  United States   US
717        Richmond        Richmond  37.5295  -77.4756  United States   US
740         Memphis         Memphis  35.1087  -89.9663  United States   US
774   Oklahoma City   Oklahoma City  35.4676  -97.5136  United States   US
788        Hartford        Hartford  41.7661  -72.6834  United States   US

    iso3            admin_name  capital  population          id  in_europe
11   USA              New York      NaN  18908608.0  1840034016      False
33   USA            California      NaN  11922389.0  1840020491      False
55   USA              Illinois      NaN   8497759.0  1840000494      False
88   USA               Florida      NaN   6080145.0  1840015149      False
90   USA                 Texas      NaN   5970127.0  1840020925      False
94   USA                 Texas      NaN   5830932.0  1840019440      False
100  USA          Pennsylvania      NaN   5683533.0  1840000673      False
122  USA               Georgia    admin   5180179.0  1840013660      False
123  USA  District of Columbia  primary   5116378.0  1840006060      False
161  USA         Massachusetts    admin   4328315.0  1840000455      False
179  USA               Arizona    admin   4064275.0  1840020568      False
198  USA              Michigan      NaN   3725908.0  1840003971      False
212  USA            Washington      NaN   3561397.0  1840021117      False
225  USA            California      NaN   3364979.0  1840021543      False
252  USA            California      NaN   3046560.0  1840021990      False
272  USA             Minnesota      NaN   2892569.0  1840007830      False
279  USA               Florida      NaN   2861173.0  1840015982      False
288  USA              New York      NaN   2736074.0  1840034030      False
296  USA              Colorado    admin   2687458.0  1840018789      False
345  USA              New York      NaN   2405464.0  1840034002      False
356  USA            California      NaN   2332836.0  1840020551      False
369  USA                Nevada      NaN   2248047.0  1840020364      False
377  USA              Maryland      NaN   2196524.0  1840001592      False
387  USA              Missouri      NaN   2130881.0  1840001651      False
399  USA                Oregon      NaN   2095808.0  1840019941      False
408  USA                 Texas      NaN   2058444.0  1840022220      False
424  USA            California    admin   1957738.0  1840021491      False
429  USA                 Texas    admin   1905945.0  1840019590      False
434  USA               Florida      NaN   1882705.0  1840015099      False
454  USA            California      NaN   1771413.0  1840021570      False
458  USA          Pennsylvania      NaN   1749091.0  1840001254      False
462  USA               Indiana    admin   1729849.0  1840030084      False
467  USA              New York      NaN   1694263.0  1840034000      False
468  USA                  Ohio      NaN   1692702.0  1840003814      False
469  USA              Missouri      NaN   1689556.0  1840008535      False
473  USA                  Ohio      NaN   1680247.0  1840000596      False
496  USA                  Ohio    admin   1572546.0  1840003760      False
532  USA              New York      NaN   1472654.0  1840033999      False
541  USA              Virginia      NaN   1443020.0  1840003871      False
544  USA        North Carolina      NaN   1427444.0  1840014557      False
592  USA             Wisconsin      NaN   1290940.0  1840003046      False
593  USA          Rhode Island    admin   1290271.0  1840003289      False
594  USA               Florida      NaN   1288298.0  1840015031      False
650  USA             Tennessee    admin   1177657.0  1840036155      False
654  USA                  Utah    admin   1173879.0  1840021383      False
660  USA        North Carolina    admin   1163152.0  1840014497      False
717  USA              Virginia    admin   1073223.0  1840001698      False
740  USA             Tennessee      NaN   1037998.0  1840015457      False
774  USA              Oklahoma    admin    998806.0  1840020428      False
788  USA           Connecticut    admin    974684.0  1840004773      False
               city      city_ascii      lat      lng country iso2 iso3  \
7         São Paulo       Sao Paulo -23.5500 -46.6333  Brazil   BR  BRA
28   Rio de Janeiro  Rio de Janeiro -22.9111 -43.2056  Brazil   BR  BRA
116  Belo Horizonte  Belo Horizonte -19.9167 -43.9333  Brazil   BR  BRA
171       Fortaleza       Fortaleza  -3.7275 -38.5275  Brazil   BR  BRA
282        Brasília        Brasilia -15.7939 -47.8828  Brazil   BR  BRA

           admin_name  capital  population          id  in_europe
7           São Paulo    admin  23086000.0  1076532519      False
28     Rio de Janeiro    admin  12592000.0  1076887657      False
116      Minas Gerais    admin   5328000.0  1076967355      False
171             Ceará    admin   4167996.0  1076567885      False
282  Distrito Federal  primary   2817068.0  1076144436      False
         city city_ascii      lat       lng country iso2 iso3 admin_name  \
0       Tokyo      Tokyo  35.6897  139.6922   Japan   JP  JPN      Tōkyō
24      Ōsaka      Osaka  34.6939  135.5022   Japan   JP  JPN      Ōsaka
46     Nagoya     Nagoya  35.1833  136.9000   Japan   JP  JPN      Aichi
195  Yokohama   Yokohama  35.4442  139.6381   Japan   JP  JPN   Kanagawa
363   Fukuoka    Fukuoka  33.5900  130.4017   Japan   JP  JPN    Fukuoka
423   Sapporo    Sapporo  43.0619  141.3544   Japan   JP  JPN   Hokkaidō
509  Kawasaki   Kawasaki  35.5167  139.7000   Japan   JP  JPN   Kanagawa
510      Kōbe       Kobe  34.6900  135.1956   Japan   JP  JPN      Hyōgo
536     Kyōto      Kyoto  35.0117  135.7683   Japan   JP  JPN      Kyōto

     capital  population          id  in_europe
0    primary  37732000.0  1392685764      False
24     admin  15126000.0  1392419823      False
46     admin   9197000.0  1392407472      False
195    admin   3757630.0  1392118339      False
363    admin   2286000.0  1392576294      False
423    admin   1959313.0  1392000195      False
509      NaN   1531646.0  1392003356      False
510    admin   1521707.0  1392978082      False
536    admin   1463723.0  1392622735      False
            city   city_ascii      lat       lng      country iso2 iso3  \
5         Manila       Manila  14.5958  120.9772  Philippines   PH  PHL
261  Quezon City  Quezon City  14.6500  121.0475  Philippines   PH  PHL

    admin_name  capital  population          id  in_europe
5       Manila  primary  24922000.0  1608618140      False
261     Quezon    admin   2960048.0  1608974097      False
            city   city_ascii      lat       lng country iso2 iso3  \
9    Mexico City  Mexico City  19.4333  -99.1333  Mexico   MX  MEX
109  Guadalajara  Guadalajara  20.6767 -103.3475  Mexico   MX  MEX
115    Monterrey    Monterrey  25.6667 -100.3000  Mexico   MX  MEX
416      Tijuana      Tijuana  32.5250 -117.0333  Mexico   MX  MEX
427     Ecatepec     Ecatepec  19.6097  -99.0600  Mexico   MX  MEX

           admin_name  capital  population          id  in_europe
9    Ciudad de México  primary  21804000.0  1484247881      False
109           Jalisco    admin   5525000.0  1484950208      False
115        Nuevo León    admin   5341171.0  1484559591      False
416   Baja California    minor   2002000.0  1484708778      False
427            México    minor   1929926.0  1484003694      False
           city  city_ascii      lat      lng country iso2 iso3  admin_name  \
20     Istanbul    Istanbul  41.0136  28.9550  Turkey   TR  TUR    İstanbul
110      Ankara      Ankara  39.9300  32.8500  Turkey   TR  TUR      Ankara
162       İzmir       Izmir  38.4200  27.1400  Turkey   TR  TUR       İzmir
271       Bursa       Bursa  40.1833  29.0500  Turkey   TR  TUR       Bursa
373       Konya       Konya  37.8667  32.4833  Turkey   TR  TUR       Konya
448      Mersin      Mersin  36.8000  34.6333  Turkey   TR  TUR      Mersin
456       Adana       Adana  37.0000  35.3213  Turkey   TR  TUR       Adana
461  Diyarbakır  Diyarbakir  37.9100  40.2400  Turkey   TR  TUR  Diyarbakır
555     Kayseri     Kayseri  38.7225  35.4875  Turkey   TR  TUR     Kayseri
561      Samsun      Samsun  41.2903  36.3336  Turkey   TR  TUR      Samsun

     capital  population          id  in_europe
20     admin  16079000.0  1792756324      False
110  primary   5503985.0  1792572891      False
162    admin   4320519.0  1792725579      False
271    admin   2901396.0  1792903330      False
373    admin   2232374.0  1792014004      False
448    admin   1814468.0  1792520282      False
456    admin   1765981.0  1792783772      False
461    admin   1732396.0  1792536241      False
555    admin   1389680.0  1792945815      False
561    admin   1368488.0  1792169057      False
         city city_ascii     lat       lng    country iso2 iso3  \
1     Jakarta    Jakarta -6.1750  106.8275  Indonesia   ID  IDN
74   Surabaya   Surabaya -7.2458  112.7378  Indonesia   ID  IDN
206     Medan      Medan  3.5894   98.6739  Indonesia   ID  IDN

         admin_name  capital  population          id  in_europe
1           Jakarta  primary  33756000.0  1360771077      False
74       Jawa Timur    admin   6998000.0  1360484663      False
206  Sumatera Utara    admin   3632000.0  1360543171      False
       city city_ascii      lat      lng   country iso2 iso3 admin_name  \
21  Karachi    Karachi  24.8600  67.0100  Pakistan   PK  PAK      Sindh
31   Lahore     Lahore  31.5497  74.3436  Pakistan   PK  PAK     Punjab

   capital  population          id  in_europe
21   admin  15738000.0  1586129469      False
31   admin  12306000.0  1586801463      False
        city city_ascii      lat      lng country iso2 iso3  \
26    Tehran     Tehran  35.6892  51.3889    Iran   IR  IRN
224  Mashhad    Mashhad  36.3264  59.5433    Iran   IR  IRN

            admin_name  capital  population          id  in_europe
26              Tehrān  primary  14148000.0  1364305026      False
224  Khorāsān-e Raẕavī    admin   3372090.0  1364123206      False
           city  city_ascii      lat       lng       country iso2 iso3  \
8         Seoul       Seoul  37.5600  126.9900  Korea, South   KR  KOR
217       Busan       Busan  35.1800  129.0750  Korea, South   KR  KOR
266     Incheon     Incheon  37.4833  126.6333  Korea, South   KR  KOR
351       Daegu       Daegu  35.8717  128.6017  Korea, South   KR  KOR
523     Gwangju     Gwangju  35.1653  126.8486  Korea, South   KR  KOR
531     Daejeon     Daejeon  36.3500  127.3850  Korea, South   KR  KOR
620       Suwon       Suwon  37.2667  127.0167  Korea, South   KR  KOR
671       Ulsan       Ulsan  35.5500  129.3167  Korea, South   KR  KOR
713     Tongjin     Tongjin  37.2333  127.2000  Korea, South   KR  KOR
723      Goyang      Goyang  37.6500  126.8000  Korea, South   KR  KOR
763    Changwon    Changwon  35.2708  128.6631  Korea, South   KR  KOR
819  Hwasu-dong  Hwasu-dong  37.1997  126.8314  Korea, South   KR  KOR
836     Sŏngnam     Songnam  37.4333  127.1500  Korea, South   KR  KOR
902    Cheongju    Cheongju  36.6333  127.4833  Korea, South   KR  KOR
963     Bucheon     Bucheon  37.5000  126.7833  Korea, South   KR  KOR

    admin_name  capital  population          id  in_europe
8        Seoul  primary  23016000.0  1410836482      False
217      Busan    admin   3453198.0  1410601465      False
266    Incheon    admin   2936117.0  1410160313      False
351      Daegu    admin   2376044.0  1410095252      False
523    Gwangju    admin   1490092.0  1410000087      False
531    Daejeon    admin   1475221.0  1410993875      False
620   Gyeonggi    admin   1234300.0  1410679777      False
671      Ulsan    admin   1150116.0  1410134602      False
713   Gyeonggi      NaN   1076369.0  1410160862      False
723   Gyeonggi    minor   1061929.0  1410511255      False
763  Gyeongnam    admin   1009998.0  1410592618      False
819   Gyeonggi      NaN    941489.0  1410037247      False
836   Gyeonggi      NaN    918771.0  1410622472      False
902   Chungbuk    admin    852018.0  1410964361      False
963   Gyeonggi    minor    781119.0  1410428222      False
           city  city_ascii      lat      lng country iso2 iso3  \
10        Cairo       Cairo  30.0444  31.2358   Egypt   EG  EGY
107        Giza        Giza  29.9870  31.2118   Egypt   EG  EGY
135  Alexandria  Alexandria  31.1975  29.8925   Egypt   EG  EGY

          admin_name  capital  population          id  in_europe
10        Al Qāhirah  primary  20296000.0  1818253931      False
107         Al Jīzah    admin   5598402.0  1818925479      False
135  Al Iskandarīyah    admin   4870000.0  1818695837      False
                  city        city_ascii      lat       lng  country iso2  \
23    Ho Chi Minh City  Ho Chi Minh City  10.7756  106.7019  Vietnam   VN
58               Hanoi             Hanoi  21.0000  105.8500  Vietnam   VN
395           Haiphong          Haiphong  20.8651  106.6838  Vietnam   VN
618            Cần Thơ           Can Tho  10.0333  105.7833  Vietnam   VN
692           Biên Hòa          Bien Hoa  10.9500  106.8167  Vietnam   VN
759            Thủ Đức           Thu Duc  10.8266  106.7609  Vietnam   VN
771           Quảng Hà          Quang Ha  15.9333  108.2667  Vietnam   VN
1149               Huế               Hue  16.4667  107.5792  Vietnam   VN
1208            Tân An            Tan An  10.9050  106.6994  Vietnam   VN
1422          Bắc Ninh          Bac Ninh  21.1833  106.0500  Vietnam   VN
1454         Hải Dương         Hai Duong  20.9397  106.3306  Vietnam   VN
1510              Vinh              Vinh  18.6667  105.6667  Vietnam   VN
1578          Tân Uyên          Tan Uyen  11.0508  106.7636  Vietnam   VN
1772            Đà Lạt            Da Lat  11.9417  108.4383  Vietnam   VN
1817         Thanh Hóa         Thanh Hoa  19.8075  105.7764  Vietnam   VN
1824         Nha Trang         Nha Trang  12.2450  109.1917  Vietnam   VN
1995          Nam Định          Nam Dinh  20.4200  106.1683  Vietnam   VN
2057          Vũng Tàu          Vung Tau  10.3833  107.1167  Vietnam   VN

In [18]:
source[source.capital == 'primary']

,city,city_ascii,lat,lng,country,iso2,iso3,admin_name,capital,population,id
0,Tokyo,Tokyo,35.6897,139.6922,Japan,JP,JPN,Tōkyō,primary,37732000.0,1392685764
1,Jakarta,Jakarta,-6.1750,106.8275,Indonesia,ID,IDN,Jakarta,primary,33756000.0,1360771077
5,Manila,Manila,14.5958,120.9772,Philippines,PH,PHL,Manila,primary,24922000.0,1608618140
8,Seoul,Seoul,37.5600,126.9900,"Korea, South",KR,KOR,Seoul,primary,23016000.0,1410836482
9,Mexico City,Mexico City,19.4333,-99.1333,Mexico,MX,MEX,Ciudad de México,primary,21804000.0,1484247881
...,...,...,...,...,...,...,...,...,...,...,...
47530,Ngerulmud,Ngerulmud,7.5006,134.6242,Palau,PW,PLW,Melekeok,primary,271.0,1585525081
47592,Adamstown,Adamstown,-25.0667,-130.1000,Pitcairn Islands,PN,PCN,NaN,primary,47.0,1612000000
47671,Plymouth,Plymouth,16.7064,-62.2158,Montserrat,MS,MSR,Saint Anthony,primary,NaN,1500711935
47843,King Edward Point,King Edward Point,-54.2833,-36.5000,South Georgia And South Sandwich Islands,GS,SGS,NaN,primary,NaN,1239048838
47867,Charlotte Amalie,Charlotte Amalie,18.3420,-64.9331,U.S. Virgin Islands,VI,VIR,Virgin Islands,primary,NaN,1850037473

In [24]:
source[source.country.isin(european_countries)].sort_values('population', ascending=False).head(100)

,city,city_ascii,lat,lng,country,iso2,iso3,admin_name,capital,population,id
17,Moscow,Moscow,55.7558,37.6172,Russia,RU,RUS,Moskva,primary,17332000.0,1643318494
35,London,London,51.5072,-0.1275,United Kingdom,GB,GBR,"London, City of",primary,11262000.0,1826645935
36,Paris,Paris,48.8567,2.3522,France,FR,FRA,Île-de-France,primary,11060000.0,1250015082
84,Madrid,Madrid,40.4169,-3.7033,Spain,ES,ESP,Madrid,primary,6211000.0,1724616994
114,Saint Petersburg,Saint Petersburg,59.9375,30.3086,Russia,RU,RUS,Sankt-Peterburg,admin,5384342.0,1643616350
...,...,...,...,...,...,...,...,...,...,...,...
1224,Tallinn,Tallinn,59.4372,24.7453,Estonia,EE,EST,Tallinn,primary,614561.0,1233260021
1231,Gothenburg,Gothenburg,57.7075,11.9675,Sweden,SE,SWE,Västra Götaland,admin,607882.0,1752059374
1242,Kryvyi Rih,Kryvyi Rih,47.9100,33.3900,Ukraine,UA,UKR,Dnipropetrovska Oblast,minor,603904.0,1804544901
1247,Yaroslavl,Yaroslavl,57.6167,39.8500,Russia,RU,RUS,Yaroslavskaya Oblast’,admin,601403.0,1643338528
1256,Vladivostok,Vladivostok,43.1333,131.9000,Russia,RU,RUS,Primorskiy Kray,admin,597240.0,1643832017

In [32]:
for country in european_countries:
    if country not in source.country.unique():
        print(country)

Vatican

In [28]:
source.country.unique()

array(['Japan', 'Indonesia', 'India', 'China', 'Philippines', 'Brazil',
       'Korea, South', 'Mexico', 'Egypt', 'United States', 'Bangladesh',
       'Thailand', 'Russia', 'Argentina', 'Nigeria', 'Turkey', 'Pakistan',
       'Vietnam', 'Iran', 'Congo (Kinshasa)', 'United Kingdom', 'France',
       'Peru', 'Angola', 'Malaysia', 'South Africa', 'Colombia',
       'Tanzania', 'Sudan', 'Hong Kong', 'Saudi Arabia', 'Chile', 'Spain',
       'Iraq', 'Singapore', 'Cameroon', 'Canada', 'Kenya', 'Burma',
       'Australia', 'Côte d’Ivoire', 'Germany', 'Afghanistan', 'Mali',
       'Jordan', 'Morocco', 'Ghana', 'Algeria', 'United Arab Emirates',
       'Bolivia', 'Greece', 'Ethiopia', 'Taiwan', 'Guatemala', 'Kuwait',
       'Hungary', 'Yemen', 'Uzbekistan', 'Ukraine', 'Korea, North',
       'Italy', 'Ecuador', 'Somalia', 'Syria', 'Zambia', 'Burkina Faso',
       'Lebanon', 'Romania', 'Sri Lanka', 'Azerbaijan', 'Madagascar',
       'Venezuela', 'Austria', 'Zimbabwe', 'Cambodia', 'Sweden', 'Cuba',
       'Belarus', 'Netherlands', 'Kazakhstan', 'Malawi', 'Poland',
       'Puerto Rico', 'Congo (Brazzaville)', 'Oman', 'Uruguay',
       'Honduras', 'Uganda', 'Guinea', 'Bulgaria', 'Costa Rica', 'Rwanda',
       'Panama', 'Senegal', 'Mongolia', 'Israel', 'Denmark', 'Finland',
       'Czechia', 'New Zealand', 'Dominican Republic', 'Portugal',
       'Ireland', 'Belgium', 'Serbia', 'Qatar', 'Libya', 'Burundi',
       'Mozambique', 'Kyrgyzstan', 'Georgia', 'Chad', 'Mauritania',
       'Armenia', 'Norway', 'Nicaragua', 'Turkmenistan', 'Niger',
       'Liberia', 'Haiti', 'Eritrea', 'Sierra Leone', 'Laos', 'Latvia',
       'Central African Republic', 'Tajikistan', 'Nepal', 'Gabon',
       'Croatia', 'Lithuania', 'Moldova', 'Papua New Guinea', 'Benin',
       'Bahrain', 'Estonia', 'Djibouti', 'Tunisia', 'Gaza Strip',
       'Jamaica', 'Macau', 'North Macedonia', 'Guinea-Bissau', 'Malta',
       'Paraguay', 'Slovakia', 'South Sudan', 'Switzerland', 'Namibia',
       'Bosnia and Herzegovina', 'Albania', 'Gambia, The', 'Lesotho',
       'Cyprus', 'El Salvador', 'Reunion', 'Equatorial Guinea',
       'Slovenia', 'Bahamas, The', 'Martinique', 'Guadeloupe', 'Botswana',
       'Suriname', 'Timor-Leste', 'Kosovo', 'West Bank', 'Guyana', 'Fiji',
       'New Caledonia', 'Montenegro', 'Curaçao', 'Mauritius', 'Iceland',
       'Maldives', 'Luxembourg', 'French Polynesia', 'Guam', 'Bhutan',
       'Togo', 'Eswatini', 'Barbados', 'Trinidad and Tobago',
       'Solomon Islands', 'Mayotte', 'Cabo Verde', 'Saint Lucia',
       'Sao Tome and Principe', 'French Guiana', 'Belize', 'Brunei',
       'Vanuatu', 'Samoa', 'Monaco', 'Aruba', 'Gibraltar', 'Jersey',
       'Marshall Islands', 'Comoros', 'Kiribati', 'Isle of Man',
       'Cayman Islands', 'Seychelles', 'Saint Vincent and the Grenadines',
       'Tonga', 'Andorra', 'Antigua and Barbuda', 'Guernsey', 'Greenland',
       'Dominica', 'Micronesia, Federated States of', 'Faroe Islands',
       'Saint Kitts and Nevis', 'Virgin Islands, British',
       'American Samoa', 'Grenada', 'San Marino',
       'Bonaire, Sint Eustatius, and Saba', 'Palau', 'Tuvalu',
       'Liechtenstein', 'Saint Martin', 'Saint Pierre and Miquelon',
       'Cook Islands', 'Turks and Caicos Islands', 'Anguilla',
       'Northern Mariana Islands', 'Saint Barthelemy',
       'Falkland Islands (Islas Malvinas)', 'Sint Maarten', 'Svalbard',
       'Christmas Island', 'Wallis and Futuna', 'Bermuda', 'Vatican City',
       'Nauru', 'Saint Helena, Ascension, and Tristan da Cunha', 'Niue',
       'Montserrat', 'Norfolk Island',
       'South Georgia and South Sandwich Islands', 'Pitcairn Islands',
       'South Georgia And South Sandwich Islands', 'U.S. Virgin Islands'],
      dtype=object)